/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dispersioncube.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dispersioncube.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Würfel.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/dispersioncube.gltf')
