/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wordmark.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wordmark.gltf')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={10000000000} near={0.01} fov={32.269} position={[0, 0, 0.154]} />
      <mesh geometry={nodes['Voronoi-Bruch'].geometry} material={nodes['Voronoi-Bruch'].material} />
    </group>
  )
}

useGLTF.preload('/wordmark.gltf')
